### ISSUE TITLE
Hardcoded path

### ISSUE THREAD

**Issue by vpavlin** [hemajv/flask-prometheus#1]
I noticed https://github.com/hemajv/flask-prometheus/blob/master/app.py#L51 - my understanding is that it would probably fail on my computer, wouldn't it?

**Comment by hemajv** [comment]
Yes, you are right. This was just for testing purpose. I am still working on moving it to production.

**Comment by vpavlin** [comment]
Sure, I just wanted to point out that things like this (hardcoded values, paths etc) should be removed/replaced with configuration option *before* you push to github - otherwise it's easy to push some credentials or secrets by mistake. So always remove hardcoded strings before you push to GH:)

**Comment by hemajv** [comment]
Definitely! It was my mistake to commit the code before I changed the parameters. Nonetheless, thank you for bringing it to my attention. I have removed the path and changed it to a system argument parameter to be passed for now.
